version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - pip3 install aws-sam-cli
  pre_build:
    commands:
      - aws --version
  build:
    commands:
      - aws serverlessrepo get-application --application-id arn:aws:serverlessrepo:us-west-1:145266761615:applications/ffmpeg-lambda-layer
      - sam build
      - sam package --s3-bucket $S3_BUCKET --output-template-file packaged_raw.yaml
  post_build:
    commands:
      # Use timestamp to force update of ApiGatewayCreateDeploymentCustomResource
      - BUILD_TIMESTAMP=$(date '+%s')
      - envsubst '${BUILD_TIMESTAMP}' < packaged_raw.yaml > packaged.yaml
artifacts:
  files:
    - packaged.yaml
