version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - pip3 install aws-sam-cli
  build:
    commands:
      - LAYER_STACK_NAME = ffmpeg-lambda-layer
      - FFMPEG_LAMBDA_LAYER = $(aws cloudformation describe-stacks --stack-name $(LAYER_STACK_NAME) --query Stacks[].Outputs[].OutputValue --output text)
      - sam build
      - sam package --parameter-overrides ParameterKey=FfmpegLambdaLayer,ParameterValue=${FFMPEG_LAMBDA_LAYER} --s3-bucket $S3_BUCKET --output-template-file packaged_raw.yaml
  post_build:
    commands:
      # Use timestamp to force update of ApiGatewayCreateDeploymentCustomResource
      - BUILD_TIMESTAMP=$(date '+%s')
      - envsubst '${BUILD_TIMESTAMP}' < packaged_raw.yaml > packaged.yaml
artifacts:
  files:
    - packaged.yaml
