AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda creating thumbnails for uploaded files and urls.

Parameters:
  FileUploadBucketName:
    Type: String
    Default: !Sub 'nva-resource-storage-${AWS::AccountId}'
    Description: Name of input bucket. Files uploaded here will be used as input for this lambda.
  ThumbnailOutputBucketName:
    Type: String
    Default: !Sub 'dlr-nva-thumbnails-${AWS::AccountId}'
    Description: Name of output bucket. Thumbnails created by this function will be stored here. This bucket is also setup to be public read.
  FfmpegLambdaVersion:
    Type: String
    Default: 1.0.0
    Description: The semantic version of the ffmpeg layer you wish to deploy.

Resources:
  DlrNvaThumbnailServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [ lambda.amazonaws.com ]
            Action: [ 'sts:AssumeRole' ]
      Policies:
        - PolicyName: writeLog
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*'
        - policyName: getInputFilePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !Sub 'arn:aws:s3:::${FileUploadBucketName}*'
        - policyName: uploadThumbnailPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:putObject
                Resource:
                  - !Sub 'arn:aws:s3:::${ThumbnailOutputBucketName}*'

  FfmpegLambdaLayer:
    Type: AWS::Serverless::Application
    Properties:
      Location: arn:aws:serverlessrepo:us-east-1:145266761615:applications/ffmpeg-lambda-layer
      SemanticVersion: !Ref FfmpegLambdaVersion

  DlrNvaThumbnailServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: thumbnail-service
      Handler: no.sikt.nva.thumbnail.ThumbnailRequestHandler::handleRequest
      Role: !GetAtt DlrNvaThumbnailServiceRole.Arn
      Environment:
        Variables:
          THUMBNAIL_BUCKET: !Ref ThumbnailOutputBucketName
      Runtime: java11
      MemorySize: 10240
      Events:
        FileUploadedEvent:
          Type: S3
          Properties:
            Bucket: !Ref FileUploadBucketName
            Events: 's3:ObjectCreated:*'
      Layers:
        - !GetAtt   FfmpegLambdaLayer.Outputs.LayerVersion

  ThumbnailBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref ThumbnailOutputBucketName